"""add settings, market athlete state, current_day

Revision ID: 0091c351c64e
Revises: ab9ccc72d5d2
Create Date: 2026-09-10 11:15:11.898186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0091c351c64e'
down_revision: Union[str, Sequence[str], None] = 'ab9ccc72d5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_length_minutes', sa.Integer(), nullable=False),
    sa.Column('ticks_per_day', sa.Integer(), nullable=False),
    sa.Column('randomness', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='settings_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_athlete_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('baseline_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_target', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_game_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id')
    )
    # market_state already holds a row, so a NOT NULL column needs a value to
    # backfill with. The model carries a Python-side default, not a server one,
    # so the server default is dropped again once the backfill is done.
    op.add_column(
        'market_state',
        sa.Column('current_day', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('market_state', 'current_day', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_state', 'current_day')
    op.drop_table('market_athlete_state')
    op.drop_table('settings')
    # ### end Alembic commands ###
