"""add sport norms

Revision ID: 0abd58c1f7cc
Revises: 0091c351c64e
Create Date: 2026-09-10 11:57:57.107109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0abd58c1f7cc'
down_revision: Union[str, Sequence[str], None] = '0091c351c64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sport_norms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=40), nullable=False),
    sa.Column('mean_perf', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('std_perf', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('athlete_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sport_norms')
    # ### end Alembic commands ###
