"""Add orders and reservations

Revision ID: 230314d57309
Revises: 7893887e8d17
Create Date: 2026-09-23 23:31:52.450098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '230314d57309'
down_revision: Union[str, Sequence[str], None] = '7893887e8d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=10), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('fund_id', sa.Integer(), nullable=True),
    # the type already exists -- trades created it. create_type=False reuses
    # it rather than failing on a second CREATE TYPE.
    sa.Column(
        'side',
        postgresql.ENUM('buy', 'sell', name='trade_side', create_type=False),
        nullable=False,
    ),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('trigger_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_day', sa.Integer(), nullable=False),
    sa.Column('expires_day', sa.Integer(), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(athlete_id IS NOT NULL AND fund_id IS NULL) OR (athlete_id IS NULL AND fund_id IS NOT NULL)', name='ck_order_one_asset'),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_expires_day'), 'orders', ['expires_day'], unique=False)
    op.create_index('ix_orders_open', 'orders', ['status', 'athlete_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    # server-default-then-drop: the default exists only to fill the rows that
    # are already there, since NOT NULL cannot be added to them otherwise. It
    # is dropped straight after, so from here the application supplies the
    # value and a row that forgets it fails loudly instead of silently zeroing.
    op.add_column(
        'holdings',
        sa.Column('reserved_quantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    )
    op.alter_column('holdings', 'reserved_quantity', server_default=None)
    op.add_column(
        'portfolio',
        sa.Column('reserved_cash', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    )
    op.alter_column('portfolio', 'reserved_cash', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'reserved_cash')
    op.drop_column('holdings', 'reserved_quantity')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index('ix_orders_open', table_name='orders')
    op.drop_index(op.f('ix_orders_expires_day'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
