"""Add league bonds

Revision ID: 7893887e8d17
Revises: de2d32d46e6b
Create Date: 2026-09-23 22:53:35.175527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7893887e8d17'
down_revision: Union[str, Sequence[str], None] = 'de2d32d46e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bond_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('term_days', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('coupon_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('bought_day', sa.Integer(), nullable=False),
    sa.Column('maturity_day', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bond_positions_maturity_day'), 'bond_positions', ['maturity_day'], unique=False)
    op.create_index(op.f('ix_bond_positions_user_id'), 'bond_positions', ['user_id'], unique=False)
    op.create_table('bond_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['bond_positions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', 'kind', 'day', name='uq_bond_txn_position_kind_day')
    )
    op.create_index(op.f('ix_bond_transactions_position_id'), 'bond_transactions', ['position_id'], unique=False)
    op.create_index(op.f('ix_bond_transactions_user_id'), 'bond_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bond_transactions_user_id'), table_name='bond_transactions')
    op.drop_index(op.f('ix_bond_transactions_position_id'), table_name='bond_transactions')
    op.drop_table('bond_transactions')
    op.drop_index(op.f('ix_bond_positions_user_id'), table_name='bond_positions')
    op.drop_index(op.f('ix_bond_positions_maturity_day'), table_name='bond_positions')
    op.drop_table('bond_positions')
    # ### end Alembic commands ###
