"""Add athlete position and sport anchor distribution

Revision ID: b30071085dc2
Revises: 1cb2a171c859
Create Date: 2026-09-12 00:33:28.906395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30071085dc2'
down_revision: Union[str, Sequence[str], None] = '1cb2a171c859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'athletes', sa.Column('position', sa.String(length=20), nullable=True)
    )
    # sport_norms already has a row per sport, so the new columns need a value
    # for them before they can be NOT NULL. The defaults describe the old
    # behaviour -- anchored on perf_mean -- and compute_sport_norms overwrites
    # them on its next run. Dropped afterwards so the model stays authoritative.
    op.add_column(
        'sport_norms',
        sa.Column(
            'anchor_stat',
            sa.String(length=40),
            nullable=False,
            server_default='perf_mean',
        ),
    )
    op.add_column(
        'sport_norms',
        sa.Column(
            'mean_anchor',
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            server_default='0',
        ),
    )
    op.add_column(
        'sport_norms',
        sa.Column(
            'std_anchor',
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            server_default='1',
        ),
    )
    for column in ('anchor_stat', 'mean_anchor', 'std_anchor'):
        op.alter_column('sport_norms', column, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sport_norms', 'std_anchor')
    op.drop_column('sport_norms', 'mean_anchor')
    op.drop_column('sport_norms', 'anchor_stat')
    op.drop_column('athletes', 'position')
    # ### end Alembic commands ###
