"""Let holdings and trades reference a fund

Revision ID: c4d0d4c304e1
Revises: 7e7847570484
Create Date: 2026-09-12 12:54:09.358782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d0d4c304e1'
down_revision: Union[str, Sequence[str], None] = '7e7847570484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Every existing row is an athlete position, so the new column arrives with
    # that as its server default -- that IS the backfill. The default is then
    # dropped so the model stays the only place the default lives.
    for table in ('holdings', 'trades'):
        op.add_column(
            table,
            sa.Column(
                'asset_type',
                sa.String(length=10),
                nullable=False,
                server_default='athlete',
            ),
        )
        op.add_column(table, sa.Column('fund_id', sa.Integer(), nullable=True))
        op.alter_column(table, 'athlete_id', existing_type=sa.INTEGER(), nullable=True)
        op.create_foreign_key(
            f'fk_{table}_fund_id', table, 'funds', ['fund_id'], ['id']
        )
        op.alter_column(table, 'asset_type', server_default=None)
        # Alembic does not autogenerate CHECK constraints; without this a row
        # could name both assets, or neither, and the ledger would be ambiguous.
        op.create_check_constraint(
            f'ck_{table[:-1] if table.endswith("s") else table}_one_asset',
            table,
            '(athlete_id IS NOT NULL AND fund_id IS NULL) OR '
            '(athlete_id IS NULL AND fund_id IS NOT NULL)',
        )

    op.create_unique_constraint(
        'uq_user_fund_holding', 'holdings', ['user_id', 'fund_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('uq_user_fund_holding', 'holdings', type_='unique')
    for table in ('holdings', 'trades'):
        name = table[:-1] if table.endswith('s') else table
        op.drop_constraint(f'ck_{name}_one_asset', table, type_='check')
        op.drop_constraint(f'fk_{table}_fund_id', table, type_='foreignkey')
        op.alter_column(table, 'athlete_id', existing_type=sa.INTEGER(), nullable=False)
        op.drop_column(table, 'fund_id')
        op.drop_column(table, 'asset_type')
