"""Add athlete retired_at

Revision ID: c7c35e26c899
Revises: b30071085dc2
Create Date: 2026-09-12 00:45:33.866315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c35e26c899'
down_revision: Union[str, Sequence[str], None] = 'b30071085dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athletes', 'retired_at')
    # ### end Alembic commands ###
