"""Add user display name

Revision ID: de2d32d46e6b
Revises: c4d0d4c304e1
Create Date: 2026-09-23 22:27:27.580302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2d32d46e6b'
down_revision: Union[str, Sequence[str], None] = 'c4d0d4c304e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Nullable first, not a server default: the backfilled value depends on
    # each row's own id, which a default cannot express. Add, fill, then
    # tighten -- the index and check go on last, once every row satisfies them.
    op.add_column('users', sa.Column('display_name', sa.String(length=20), nullable=True))
    op.execute(sa.text("UPDATE users SET display_name = 'trader-' || id"))
    op.alter_column('users', 'display_name', existing_type=sa.String(length=20), nullable=False)
    op.create_index(
        'uq_users_display_name_lower', 'users',
        [sa.literal_column('lower(display_name)')], unique=True,
    )
    # Alembic does not autogenerate CHECK constraints
    op.create_check_constraint(
        'ck_user_display_name', 'users', "display_name ~ '^[A-Za-z0-9_-]{3,20}$'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_user_display_name', 'users', type_='check')
    op.drop_index('uq_users_display_name_lower', table_name='users')
    op.drop_column('users', 'display_name')
